name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  playwright-standard-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          TESTCHIMP_API_KEY: ${{ secrets.TESTCHIMP_API_KEY }}
          TESTCHIMP_PROJECT_ID: ${{ secrets.TESTCHIMP_PROJECT_ID }}
          TESTCHIMP_TESTS_FOLDER: "tests"
          TESTCHIMP_API_URL: "https://featureservice-staging.testchimp.io"
          TESTCHIMP_RELEASE: "default"
          TESTCHIMP_ENV: "QA"
